### ISSUE TITLE
Belopp för djurhållning inte klar

### ISSUE THREAD

**Issue by hakan-liden** [blinfo/Bodil#1]
Formulär finns men det sparas inte än. // Klart

**Comment by xperjon** [comment]
Blir ju bra det här!

En annan grej. Erika S undrade över lösenordet till mysqldatabasen på intranätet. Jag antar att du vet det. Du kan väl snacka med henne när du är tillbaka.

Ses!

**Comment by hakan-liden** [comment]
Kvar att göra:
Tag för att presentera beloppen.
